### ISSUE TITLE
SPAM on your site

### ISSUE THREAD

**Issue by mnaylorwooster** [newjersey/business-programs#13]
Hello,

I noticed this page as a part of your COVID-19 resources. I'm not sure that it belongs there.

https://programs.business.nj.gov/pbvsg/09-mr-ryder-kihn-jr-5/

-Mike

**Comment by rossdakin** [comment]
@mnaylorwooster – many thanks for pointing this out.

We initially set this site up at programs.business.nj.gov, and when migrating to assistance.business.nj.gov we did not remove the original DNS record, as GitHub seemed to create an automatic redirect from it.

However, someone else then replicated the CNAME and essentially masqueraded as our site. According to GitHub, this is apparently a known abuse vector, and they have a fix in the works, just not in place yet. I learned something today!

I've deleted the DNS record, so this should be resolved going forward.

Thanks again.
